name: Publish a release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git credentials
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.2.6'
      
      - name: Install Nim build dependencies
        run: sudo apt-get install musl-dev musl-tools
      
      - name: Bump version and push tag
        run: ./bin/release

      - name: Build binary
        run: ./bin/build

      - name: Set current tag
        run:
          TAG=$(nimble dump | grep "version:" | sed 's/version: //' | sed 's/"//g')
          echo "::set-env name=TAG::$TAG"

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tooling_webserver
          asset_name: tooling_webserver
          tag: $TAG
          overwrite: true
